services:
  orchestrator:
    build: .
    image: martinelli/orchestrator:latest
    container_name: orchestrator
    restart: unless-stopped
    ports:
      - "3310:80"
    depends_on:
      - stats-api

  stats-api:
    build: ./api
    image: martinelli/orchestrator-stats:latest
    container_name: orchestrator-stats
    restart: unless-stopped
    ports:
      - "8900:8000"
    environment:
      SERVER_ID: ${SERVER_ID:-MTLADVL063}
      # NODE_PORT: "8900"    # porta exposta dos outros nós (padrão 8900)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .:/app/repo
